#include"linklist.h"

using namespace std;
int main(){
    linklist st1;
    st1.pushback(1);
    st1.pushback(2);
    st1.pushback(3);
    st1.pushback(4);
    st1.print();
    st1.pushhead(10);
    st1.pushhead(11);
    st1.pushhead(12);
    st1.pushhead(13);
    st1.print();
    st1.delethead();
    st1.delethead();
    st1.delethead();
    st1.print();
    st1.deletback();
    st1.deletback();
    st1.deletback();
    st1.print();
    st1.deletback();
    st1.deletback();
    st1.print();
    st1.pushback(1);
    st1.pushback(3);
    st1.pushback(5);
    st1.pushback(99);
    st1.pushback(4);
    int i = st1.finddata(99);
    cout<<i<<endl;
    int j = st1.finddata(3);
    cout<<j<<endl;
    st1.deletpos(j);
    st1.print();
    int k = st1.finddata(4);
    cout<<k<<endl;
    int h = st1.finddata(999);
    cout<<h<<endl;
    st1.print();
    int p = st1.finddata(99);
    st1.deletpos(p);
    st1.print();
    st1.pushback(66);
    st1.pushback(55);
    st1.pushback(44);
    st1.pushback(33);
    st1.pushback(22);
    st1.print();
    int y =st1.finddata(66);
    cout<<y<<endl;
    st1.pushafterpos(y,999);
    st1.pushbeforepos(y,888);
    st1.print();
    int ooo = st1.finddata(22);
    st1.pushafterpos(ooo,11);
    st1.print();
    int yy = st1.checkdatapos(3);
    cout<<yy<<endl;
}